* Literate Paradigm Configuration File for Emacs - May 2019.

** Introduction.

TODO - description of what literate programming is and how it works
with Emacs and Org-mode.

** Information About Document Structure.

TODO - How document is broken down. Initial thoughts.

- Configuration required to get other things working.

- Appearance 
    Set theme/appearance
    Set modeline theme
    Font configuration

- Programming
  - C/C++
    Python
    Clojure
    
- Text editing
  - HTML
    LaTeX
    Spell checking
    Text linting


** Package Management.

Over the years I have been using Emacs I have had to deal with various
approaches to the issue of plug-ins and packages.  For a long time it
seemed you had to download the code and unpack it somewhere
appropriate, then link that location in the configuration file,
compile the code etc. And while it worked almost all the time, it was
often messy, and if there were dependencies they had to be resolved
manually. 

When I decided to start running the cutting edge Emacs versions (self
compiled) I decided that I should run the latest versions of the
packages as well and started pulling everything from their various Git
repositories. This worked quite well, and I could run a simple bash
process to update the packages as required, essentially walking the
folders and running 'git pull' for each package, and then recompiling
as required. It worked, but it was unneccesarily fiddly!

Then, along came the package repositories. These online stores provide
regularly updated lists of curated packages. The first block of code
below plumbs in the 'Melpa' repository. The packages may not be quite
as up to date as the Git repositories (though they are close) but
updating them is much simpler, involving running
'packages-list-packages', loading the package list, hitting u (update)
which will identify the packages for which there are updates, and the
x (eXecute) to update the packages that have an update available. 

The second innovation was the 'use-package' plug-in. This allows
automatic installation of packages by giving '(use-package packname)'
in the code.

#+BEGIN_SRC emacs-lisp
  (require 'package)		
  (add-to-list 'package-archives
  '("melpa-stable" . "https://stable.melpa.org/packages/") t)
  (package-initialize)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(require 'use-package)
#+END_SRC
    

** Appearance.

Out of the box Emacs isn't ugly, it is just staid. And it uses a lot
of screen real-estate which I can put to better use. 

*** Reclaiming Screen Real-Estate.

Start by removing the unneccesary menu bar and tool bar from the top
of the screen and the scroll bar on the right hand side. Once that is
done I'll know the initialisation is working and I can commit the
first configuration.

#+BEGIN_SRC emacs-lisp
  (menu-bar-mode 0)			; Turn off menu bar
  (tool-bar-mode 0)			; Turn off tool bar
  (blink-cursor-mode 0)			; Stop cursor blinking
  (scroll-bar-mode 0)			; Don't need the scrollbar
  (display-time-mode 1)			; Do put time in mode line.
#+END_SRC

*** Switch Off the Start-Up Message.

I know that I'm using Emacs, I just started the program, so I don't
need to be reminded of that fact. This code switches off the start-up
message.

#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)	; switch off splash screen.
#+END_SRC

*** Set A Nice Font.

If you are going to spend a lot of time looking at text, you might as
well make sure that it is a pleasant font to look at.

#+BEGIN_SRC emacs-lisp
  (set-face-attribute 'default nil
  :font "Inconsolata Medium"
  :height 85)				; height 85 slightly easier to read.
#+END_SRC

There was a long discussion on Reddit (/r/emacs) about preferred fonts
for programming and the like. I think I like the font, but I may go
for a larger size.

TODO - track down the discussion and look at alternative recommendations.

*** Highlight the Current Line.

To help guide the eye when writing Emacs supports highlighting of the
current line (the line where the cursor is).

#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode 1)			; highlight current line.
#+END_SRC

This highlighting is reliant on the colour scheme being used within
Emacs, so isn't always as useful as it is in this default setup where
the highlighted line has a green background against the white of the
rest of the screen.
*** Line Numbering.

As files get longer, being able to refer to a location by its line
number becomes more desirable.  This is especially the case when I
start dabbling in programming as it will help locate errors which I
will, inevitably make.

#+BEGIN_SRC emacs-lisp
  (global-linum-mode t)
#+END_SRC

