* Literate Paradigm Configuration File for Emacs - May 2019.

** Introduction.

TODO - description of what literate programming is and how it works
with Emacs and Org-mode.

** Information About Document Structure.

TODO - How document is broken down. Initial thoughts.

- Configuration required to get other things working.

- Appearance 
  - Remove screen furniture I don't want
    Set theme/appearance
    Set modeline theme
    Font configuration

- Programming
  - C/C++
    Python
    Clojure
    
- Text editing
  - HTML
    LaTeX
    Spell checking
    Text linting
    

** Appearance.

Out of the box Emacs isn't ugly, it is just staid. And it uses a lot
of screen real-estate which I can put to better use. 

Start by removing the unneccesary menu bar and tool bar from the top
of the screen and the scroll bar on the right hand side. Once that is
done I'll know the initialisation is working and I can commit the
first configuration.

#+BEGIN_SRC emacs-lisp
  (menu-bar-mode 0)			; Turn off menu bar
  (tool-bar-mode 0)			; Turn off tool bar
  (blink-cursor-mode 0)			; Stop cursor blinking
  (scroll-bar-mode 0)			; Don't need the scrollbar
  (display-time-mode 1)			; Do put time in mode line.
#+END_SRC
